[package]
name = "os_utils"
version = "0.1.0"
authors = ["TRACIP SAS <contact@tracip.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.8"
csv = "1.1"
encoding_rs = "0.8"
encoding_rs_io = "0.1"
